#!/bin/bash
# combustion: network
# script generated with https://opensuse.github.io/fuel-ignition/

# Redirect output to the console
exec > >(exec tee -a /dev/tty0) 2>&1

# Registration on SUSE system
test -e /etc/os-release && os_release='/etc/os-release' || os_release='/usr/lib/os-release'
grep -q 'cpe:.*:suse:' "${os_release}"
if [[ $? == 0 ]]; then
 if ! which SUSEConnect > /dev/null 2>&1; then
    zypper --non-interactive install suseconnect-ng
 fi
 SUSEConnect --email EMAIL --url https://scc.suse.com --regcode REGCODE
fi

 # only useful for Podman 5.x
 curl -O -L --output-dir /etc/containers https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/susecon.pod

 # demo containers
 curl -O -L --output-dir /etc/containers/systemd https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/mariadb.container
 curl -O -L --output-dir /etc/containers/systemd https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/notify-systemd.py
 curl -O -L --output-dir /etc/containers/systemd https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/wordpress.container
 curl -O -L --output-dir /etc/containers/systemd https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/wordpress.network
 
 # additional example 
 curl -O -L --output-dir /etc/containers https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/susecon.yaml
 curl -O -L --output-dir /etc/containers https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/susecon.kube

 # health-checker scripts
 curl -O -L --output-dir /usr/libexec/health-checker https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/VM/deploy-container/podman-container.sh
 curl -O -L --output-dir /usr/libexec/health-checker https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/VM/deploy-container/sshd.sh
 chmod +x /usr/libexec/health-checker/podman-container.sh /usr/libexec/health-checker/sshd.sh  

 # dockerfile to build container locally
 mkdir -p /root/container
 curl -O -L --output-dir /root/container https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/Dockerfile
 curl -O -L --output-dir /root/container https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/wp-config.php
 curl -O -L --output-dir /root/container https://raw.githubusercontent.com/fcrozat/SUSECON-demos/main/containers/wordpress/build.sh
 chmod +x /root/container/build.sh

# Leave a marker
echo "Configured with combustion" > /etc/issue.d/combustion
