#!/bin/bash
# combustion: network
# script generated with https://opensuse.github.io/fuel-ignition/

# Redirect output to the console
exec > >(exec tee -a /dev/tty0) 2>&1

# Registration on SUSE system
test -e /etc/os-release && os_release='/etc/os-release' || os_release='/usr/lib/os-release'
grep -q 'cpe:.*:suse:' "${os_release}"
if [[ $? == 0 ]]; then
 if ! which SUSEConnect > /dev/null 2>&1; then
    zypper --non-interactive install suseconnect-ng
 fi
 SUSEConnect --email EMAIL --url https://scc.suse.com --regcode REGCODE
# mkdir -p /usr/local/libexec/health-checker
 curl -O -L --output-dir /usr/libexec/health-checker https://github.com/fcrozat/SUSECON-demos/raw/main/VM/reliability/sshd.sh
 chmod +x /usr/libexec/health-checker/sshd.sh
fi

# Leave a marker
echo "Configured with combustion" > /etc/issue.d/combustion
